#!/usr/bin/env python3
"""
Script to check that each playlist's song_names list has an even number of songs.
If a list has an odd number, it adds a title from a provided list.
"""

import json
import random
from typing import List, Dict, Any

def check_and_fix_playlist_lengths(
    json_file_path: str, 
    backup_titles: List[str],
    fix_mode: bool = False,
    target_length: int = 30
) -> Dict[str, Any]:
    """
    Check playlist song lengths and optionally fix them to have exactly 30 songs.
    
    Args:
        json_file_path: Path to the lofi_playlist_data.json file
        backup_titles: List of song titles to use when padding lists
        fix_mode: If True, will modify the JSON file. If False, only reports issues.
        target_length: Target number of songs per playlist (default: 30)
    
    Returns:
        Dictionary with results of the check/fix operation
    """
    
    # Load the JSON data
    with open(json_file_path, 'r') as f:
        lofi_playlist_data = json.load(f)
    
    results = {
        'total_playlists': len(lofi_playlist_data),
        'incorrect_length_playlists': [],
        'fixed_playlists': [],
        'errors': [],
        'target_length': target_length
    }
    
    modified = False
    
    for i, playlist in enumerate(lofi_playlist_data):
        try:
            song_count = len(playlist['song_names'])
            playlist_title = playlist.get('title', f'Playlist {i}')
            
            if song_count != target_length:  # Not exactly 30 songs
                results['incorrect_length_playlists'].append({
                    'index': i,
                    'title': playlist_title,
                    'current_count': song_count,
                    'needs_added': max(0, target_length - song_count),
                    'needs_removed': max(0, song_count - target_length)
                })
                
                if fix_mode:
                    if song_count < target_length:
                        # Need to add songs
                        songs_to_add = target_length - song_count
                        if len(backup_titles) == 0:
                            raise ValueError(f"No backup titles available to add {songs_to_add} songs")
                        
                        added_titles = []
                        for _ in range(songs_to_add):
                            chosen_title = random.choice(backup_titles)
                            playlist['song_names'].append(chosen_title)
                            added_titles.append(chosen_title)
                        
                        modified = True
                        
                        results['fixed_playlists'].append({
                            'index': i,
                            'title': playlist_title,
                            'old_count': song_count,
                            'new_count': target_length,
                            'action': 'added',
                            'added_titles': added_titles,
                            'songs_modified': songs_to_add
                        })
                    
                    elif song_count > target_length:
                        # Need to remove songs (remove from the end)
                        songs_to_remove = song_count - target_length
                        removed_titles = playlist['song_names'][-songs_to_remove:]
                        playlist['song_names'] = playlist['song_names'][:-songs_to_remove]
                        
                        modified = True
                        
                        results['fixed_playlists'].append({
                            'index': i,
                            'title': playlist_title,
                            'old_count': song_count,
                            'new_count': target_length,
                            'action': 'removed',
                            'removed_titles': removed_titles,
                            'songs_modified': songs_to_remove
                        })
                    
        except Exception as e:
            results['errors'].append({
                'index': i,
                'error': str(e)
            })
    
    # Save the modified data to a new file if changes were made
    if modified and fix_mode:
        # Create new file with '_fixed' suffix
        import os
        base_name, ext = os.path.splitext(json_file_path)
        fixed_path = f"{base_name}_fixed{ext}"
        
        with open(fixed_path, 'w') as f:
            json.dump(lofi_playlist_data, f, indent=2)
        print(f"✅ Fixed playlist data saved to new file: {fixed_path}")
        print(f"📄 Original file unchanged: {json_file_path}")
        
        results['fixed_file_path'] = fixed_path
    
    return results

def print_report(results: Dict[str, Any]):
    """Print a formatted report of the check results."""
    
    print("\n" + "="*60)
    print("🎵 LOFI PLAYLIST LENGTH CHECK REPORT")
    print("="*60)
    
    print(f"\n📊 Total playlists checked: {results['total_playlists']}")
    print(f"🎯 Target length: {results['target_length']} songs per playlist")
    print(f"⚠️  Playlists with incorrect length: {len(results['incorrect_length_playlists'])}")
    print(f"✅ Playlists fixed: {len(results['fixed_playlists'])}")
    print(f"❌ Errors encountered: {len(results['errors'])}")
    
    if results['incorrect_length_playlists']:
        print(f"\n🔍 PLAYLISTS WITH INCORRECT LENGTH (not {results['target_length']} songs):")
        print("-" * 50)
        for playlist in results['incorrect_length_playlists']:
            status = ""
            if playlist['needs_added'] > 0:
                status = f"needs +{playlist['needs_added']} songs"
            elif playlist['needs_removed'] > 0:
                status = f"needs -{playlist['needs_removed']} songs"
            
            print(f"  [{playlist['index']}] {playlist['title']}")
            print(f"      Current: {playlist['current_count']} songs ({status})")
    
    if results['fixed_playlists']:
        print("\n🔧 FIXED PLAYLISTS:")
        print("-" * 40)
        for playlist in results['fixed_playlists']:
            print(f"  [{playlist['index']}] {playlist['title']}")
            print(f"      {playlist['old_count']} → {playlist['new_count']} songs")
            
            if playlist['action'] == 'added':
                print(f"      Added {playlist['songs_modified']} songs:")
                for title in playlist['added_titles']:
                    print(f"        + '{title}'")
            elif playlist['action'] == 'removed':
                print(f"      Removed {playlist['songs_modified']} songs:")
                for title in playlist['removed_titles']:
                    print(f"        - '{title}'")
    
    if results['errors']:
        print("\n❌ ERRORS:")
        print("-" * 40)
        for error in results['errors']:
            print(f"  Playlist [{error['index']}]: {error['error']}")
    
    # Show output file info if fixes were applied
    if results.get('fixed_file_path'):
        print(f"\n📁 OUTPUT FILE:")
        print(f"   Fixed data saved to: {results['fixed_file_path']}")
        print(f"   Original file preserved: unchanged")

def main():
    """Main function to run the script."""
    
    # Path to your lofi playlist data
    json_file_path = '/Users/jordanpatel/Git/lofi-channel/lofi_playlist_data.json'
    
    # TODO: Add your backup titles here
    backup_titles = [
        # Add your list of backup song titles here
        "Luminous Morning",
        "Lazy Melody",
        "Wistful Glow",
        "Daybreak Light",
        "Hazy Stream",
        "Late Night in the Rain",
        "Loop of Moonlight",
        "Cafe of Waves",
        "Velvet Rain",
        "Uplifting Letters",
        "Amber Starlight",
        "Peaceful Shore",
        "Uplifting Golden Hour",
        "Wind and Echo",
        "Melody of Waves",
        "Midnight Rain",
        "Flow of Branches",
        "Easy Rhythm",
        "Snow and Shadows",
        "Wistful Sunrise",
        "Reflections of Sea",
        "Hazy Forest",
        "Mellow Golden Hour",
        "Sunset in the City",
        "Ivory First Light",
        "Afternoon Dream",
        "Valley and Reflections",
        "Fields and Pages",
        "Quiet Sky",
        "Noon in the City",
        "Afternoon Drift",
        "Lounge of Ocean",
        "Soft Steps",
        "River and Harmony",
        "Nightfall Light",
        "Haze of Ocean",
        "Golden Hour Steps",
        "Breezy Loop",
        "Frames of Horizon",
        "Soothing Moonlight",
        "Haze of Moonlight",
        "Gentle Pages",
        "Peaceful Afternoon",
        "Sunrise Chapters",
        "Window of Sunlight",
        "Stroll of Leaves",
        "Rain and Harmony",
        "Valley and Drift",
        "Sunlight and Loop",
        "Late Night in the Cafe",
        "Dusk in the Rain",
        "Sunset in the Cafe",
        "Hopeful Late Night",
        "Crimson Fog",
        "Flow of Meadow",
        "Fog and Shadows",
        "Wistful Afternoon",
        "Meadow and Chapters",
        "Frames of Fields",
        "Afternoon Steps",
        "Quiet Room",
        "Hopeful Nightfall",
        "Twilight in the Valley",
        "Soothing Valley",
        "Rain and Window",
        "Lounge of Wind",
        "Mellow Echo",
        "Faint Stories",
        "Midnight Haze",
        "Chapters of Sunlight",
        "Mist and Echo",
        "Azure Dawn",
        "Groove of Meadow",
        "Gentle Lounge",
        "Shimmering Golden Hour",
        "Morning Lounge",
        "Snow and Moments",
        "Lazy Glow",
        "Drowsy Clouds",
        "Dreamy Evening",
        "Rain and Moments",
        "First Light in the City",
        "Pastel Dusk",
        "Morning Cafe",
        "Twilight Dusk",
        "Wistful Stroll",
        "Moments of Starlight",
        "Golden Pages",
        "Evening in the Forest",
        "Velvet Sky",
        "Easy Sunset",
        "Sunlight and Reflections",
        "Morning Pages",
        "Morning in the Cafe",
        "Quiet Ocean",
        "Blissful Late Night",
        "First Light Shadows",
        "Snow and Reflections",
        "Blissful Horizon",
        "Rain and Glow",
        "Hopeful Sunset",
        "Easy Stream",
        "Uplifting Lounge",
        "Sky and Rhythm",
        "Sea and Harmony",
        "Quiet Breeze",
        "Evening Nightfall",
        "Dreamy Cafe",
        "Sunset Window",
        "Twilight Melody",
        "Breeze and Room",
        "Twilight Letters",
        "River and Window",
        "Ivory Late Night",
        "Shimmering Leaves",
        "Fading Pages",
        "Frosted Garden",
        "Fading Window",
        "Drowsy Flow",
        "Soothing Dusk",
        "Frosted Groove",
        "Cheerful Chapters",
        "Luminous Golden Hour",
        "Azure Nightfall",
        "Tranquil Harmony",
        "Evening Moments",
        "Cozy Mist",
        "Serene Evening",
        "Starlight and Room",
        "River and Corner",
        "Drowsy Drift",
        "Drowsy Loop",
        "Crimson Haze",
        "Hazy Haze",
        "Evening Serenade",
        "Sea and Light",
        "Ocean and Haze",
        "Soft Noon",
        "Quiet Lounge",
        "Petals and Drift",
        "Horizon and Glow",
        "Serenade of Fields",
        "Mist and Flow",
        "Golden Letters",
        "Fading Daybreak",
        "Snow and Whisper",
        "Afternoon in the Garden",
        "Drowsy Ocean",
        "Letters of Mountains",
        "Serene Meadow",
        "Noon in the Valley",
        "Quiet Window",
        "Daybreak in the Forest",
        "Warm Midnight",
        "Sunrise in the Rain",
        "Faint Room",
        "Golden Hour Groove",
        "First Light Cafe",
        "Sky and Flow",
        "Playful Groove",
        "Lounge of Rain",
        "Cheerful Midnight",
        "Crimson Petals",
        "Golden Rhythm",
        "Chapters of Forest",
        "Cheerful Ocean",
        "Waves and Stories",
        "Morning Horizon",
        "Chill Evening",
        "Ivory Petals",
        "Light of Leaves",
        "Golden Hour Flow",
        "Midnight Midnight",
        "Faint Whisper",
        "Shimmering Breeze",
        "Lazy Cafe",
        "Dream of Mist",
        "Hopeful Afternoon",
        "Pastel Noon",
        "Velvet Daybreak",
        "Shimmering Midnight",
        "Mist and Corner",
        "Dreamy Sunlight",
        "Dawn in the Rain",
        "Dawn in the Garden",
        "Drift of Breeze",
        "Starlight and Window",
        "Sunny Dusk",
        "Calm Meadow",
        "Cozy Meadow",
        "First Light Glow",
        "Amber Drift",
        "Crimson Nightfall",
        "Harmony of Wind",
        "Morning in the Forest",
        "Garden and Serenade",
        "Wistful Forest",
        "Dawn Steps",
        "Daybreak Harmony",
        "Crimson Reflections",
        "Twilight Stories",
        "Meadow and Echo",
        "Drowsy Mist",
        "Midnight in the Cafe",
        "Morning Drift",
        "Leaves and Corner",
        "Evening in the Valley",
        "Morning Haze",
        "Faint Meadow",
        "Morning Reflections",
        "Morning Dream",
        "Soothing Sunset",
        "Dawn Lounge",
        "Mellow Late Night",
        "River and Light",
        "Sunset Pages",
        "Ivory Noon",
        "Noon Whisper",
        "Pastel First Light",
        "Serenade of Clouds",
        "Dream of Leaves",
        "Evening Melody",
        "Faint Nightfall",
        "Morning in the Rain",
        "Melody of Stream",
        "Nightfall in the Rain",
        "Gentle Flow",
        "Drowsy Light",
        "Azure Twilight",
        "First Light Rhythm",
        "Whisper of Mist",
        "Window of Starlight",
        "Shore and Flow",
        "Afternoon Reflections",
        "Nightfall in the Garden",
        "Stream and Drift",
        "Dreamy Afternoon",
        "Fading Letters",
        "Tranquil Chapters",
        "Hazy Ocean",
        "Chapters of Branches",
        "Amber Haze",
        "Echo of Sky",
        "Golden Glow",
        "Bright Evening",
        "Sunset Corner",
        "Dusk Haze",
        "Sunrise Letters",
        "Dawn in the Valley",
        "Dusk Loop",
        "Moments of Rain",
        "Fog and Stroll",
        "Afternoon in the Cafe",
        "Ivory Daybreak",
        "Shimmering Wind",
        "First Light in the Forest",
        "Amber Dusk",
        "Hazy Breeze",
        "Sunset Groove",
        "Bright Haze",
        "Meadow and Frames",
        "Gentle Melody",
        "Luminous Letters",
        "Garden and Dream",
        "Flow of Sunlight",
        "Evening Stroll",
        "Mist and Frames",
        "Frames of Sunlight",
        "Evening Rhythm",
        "Soft Rain",
        "Waves and Flow",
        "Twilight Whisper",
        "Golden Hour in the Garden",
        "Twilight Petals",
        "Afternoon Flow",
        "Bright Dusk",
        "Shimmering Melody",
        "Cozy Glow",
        "Faint Mist",
        "Azure Glow",
        "Sunny Echo",
        "Letters of Waves",
        "Noon in the Garden",
        "Evening Clouds",
        "Faint Corner",
        "Evening Sky",
        "Golden Hour in the City",
        "Sea and Lounge",
        "Soothing Garden",
        "Ocean and Serenade",
        "Room of Petals",
        "Waves and Echo",
        "Fog and Pages",
        "Hazy Waves",
        "Mist and Drift",
        "Morning Chapters",
        "Drift of Meadow",
        "Morning in the City",
        "Cozy Breeze",
        "Fading Afternoon",
        "Blissful Rain",
        "Dreamy Sunset",
        "Mellow Evening",
        "Soft First Light",
        "Starlight and Harmony",
        "Branches and Haze",
        "Pages of Waves",
        "Azure Sunlight",
        "Shore and Letters",
        "Golden Hour in the Valley",
        "Mellow Starlight",
        "First Light Stories",
        "Rhythm of Sea",
        "Shadows of Starlight",
        "Crimson Pages",
        "Quiet Pages",
        "Cozy Clouds",
        "Reflections of Shore",
        "Afternoon Echo",
        "Sky and Room",
        "Echo of Waves",
        "Moonlight and Chapters",
        "Crimson Shore",
        "First Light in the Garden",
        "Wind and Chapters",
        "Luminous Loop",
        "Steps of Sunlight",
        "Groove of Fog",
        "Soothing Noon",
        "Moments of Meadow",
        "Ivory Snow",
        "Cheerful Haze",
        "Faint Haze",
        "Amber Horizon",
        "Sunrise Rhythm",
        "Dawn Loop",
        "Tranquil Nightfall",
        "Chill Window",
        "Wind and Lounge",
        "Forest and Loop",
        "Valley and Room",
        "Blissful Stream",
        "Starlight and Cafe",
        "Stream and Reflections",
        "Chill Stream",
        "First Light in the Valley",
        "Moonlight and Loop",
        "Corner of Meadow",
        "Sunset in the Valley",
        "Luminous Sunset",
        "Drowsy Frames",
        "Sunny Afternoon",
        "Fog and Glow",
        "Sky and Lounge",
        "Stories of Ocean",
        "Fields and Groove",
        "Chill Drift",
        "Breeze and Drift",
        "Snow and Lounge",
        "Rain and Groove",
        "Dream of Forest",
        "Melody of Snow",
        "Branches and Light",
        "Dawn in the City",
        "Midnight Dream",
        "Breezy Shore",
        "Soft Pages",
        "Afternoon Whisper",
        "Frosted Drift",
        "Stories of Sunlight",
        "Waves and Window",
        "Hopeful Mist",
        "Fading Dusk",
        "Uplifting Corner",
        "Sunlight and Stroll",
        "Chill Golden Hour",
        "Fading Sea",
        "Stories of Wind",
        "Room of Ocean",
        "Sea and Moments",
        "Evening Harmony",
        "Cheerful Daybreak",
        "Faint Echo",
        "Light of Starlight",
        "Morning Golden Hour",
        "Sunset Steps",
        "Sunrise Dream",
        "Pastel Sunset",
        "Soothing Golden Hour",
        "Sunrise Lounge",
        "Clouds and Serenade",
        "Daybreak Stroll",
        "Mountains and Loop",
        "Afternoon Room",
        "Twilight Sky",
        "Pastel Valley",
        "Mist and Melody",
        "Luminous Sunrise",
        "Pages of Sunlight",
        "Meadow and Window",
        "Horizon and Dream",
        "Whisper of Ocean",
        "Cheerful Petals",
        "Sunrise Drift",
        "Late Night in the Valley",
        "Blissful Cafe",
        "Dreamy Nightfall",
        "Evening in the Rain",
        "Afternoon Glow",
        "Stroll of Meadow",
        "Dawn Drift",
        "Breezy Midnight",
        "Uplifting Cafe",
        "Breeze and Frames",
        "Sunset Letters",
        "Sunrise Flow",
        "Tranquil Dream",
        "Shimmering Afternoon",
        "Forest and Glow",
        "Morning First Light",
        "Dreamy Branches",
        "Cheerful Shore",
        "Letters of Moonlight",
        "Soft Petals",
        "Frosted Dusk",
        "Whisper of Shore",
        "Velvet Light",
        "Breeze and Rhythm",
        "Sunny Shadows",
        "Whisper of Petals",
        "Shimmering Dusk",
        "Lounge of Starlight",
        "Hazy Sunrise",
        "Melody of Fog",
        "Hazy Dawn",
        "Blissful First Light",
        "Frosted Midnight",
        "Gentle Sunset",
        "Mellow Petals",
        "Sky and Loop",
        "Playful Lounge",
        "Calm Breeze",
        "Playful Waves",
        "Quiet Moonlight",
        "Branches and Loop",
        "First Light in the Cafe",
        "Morning Stories",
        "Room of Meadow",
        "Mellow Daybreak",
        "Cozy Flow",
        "Mist and Pages",
        "Easy Window",
        "Golden Rain",
        "Groove of Horizon",
        "Pastel Fields",
        "Gentle Serenade",
        "Frames of Sea",
        "Peaceful Clouds",
        "Echo of River",
        "Haze of Stream",
        "Warm Leaves",
        "Stroll of Clouds",
        "Sunrise Reflections",
        "Noon Frames",
        "Frosted Dawn",
        "Daybreak Groove",
        "Tranquil Serenade",
        "Afternoon in the Valley",
        "Shadows of Sky",
        "Sunlight and Dream",
        "Twilight Garden",
        "Golden Hour Cafe",
        "Waves and Shadows",
        "Moonlight and Pages",
        "Moonlight and Dream",
        "Soothing Chapters",
        "Nightfall Serenade",
        "Sunrise Light",
        "Stream and Chapters",
        "Midnight Sky",
        "Golden Mountains",
        "Groove of Clouds",
        "Tranquil Horizon",
        "Stroll of Mist",
        "Reflections of River",
        "River and Whisper",
        "Cheerful Dawn",
        "Gentle Dawn",
        "Mist and Cafe",
        "Starlight and Dream",
        "Echo of Leaves",
        "Wistful Harmony",
        "Lazy Sea",
        "Window of Fields",
        "Sunny Starlight",
        "Playful Meadow",
        "Golden Sky",
        "Ivory Dawn",
        "Corner of Moonlight",
        "Groove of Breeze",
        "Sunrise in the Cafe",
        "Wistful First Light",
        "Blissful Room",
        "Whisper of Leaves",
        "Petals and Stories",
        "Sunlight and Shadows",
        "Ivory Serenade",
        "Soothing Echo",
        "Harmony of Waves",
        "Dusk Moments",
        "Moonlight and Rhythm",
        "Midnight Room",
        "Calm Snow",
        "Daybreak Loop",
        "Drowsy Snow",
        "Shore and Rhythm",
        "Forest and Haze",
        "Stream and Cafe",
        "Midnight in the Forest",
        "Room of Sunlight",
        "Midnight in the Garden",
        "Golden Hour Stories",
        "Dream of Sky",
        "Hopeful Chapters",
        "Wistful Reflections",
        "Evening in the City",
        "Steps of Sea",
        "Breeze and Corner",
        "Ivory Evening",
        "Moments of Stream",
        "Sky and Steps",
        "Nightfall Cafe",
        "Nightfall in the Forest",
        "Bright Dawn",
        "Quiet Mist",
        "Fading Dawn",
        "Shore and Harmony",
        "Sky and Drift",
        "Waves and Letters",
        "Ocean and Dream",
        "Mellow Glow",
        "Moonlight and Letters",
        "Sky and Cafe",
        "Chapters of Petals",
        "Morning Frames",
        "Serenade of Fog",
        "Mist and Steps",
        "Hopeful Midnight",
        "Serene Morning",
        "Mellow Letters",
        "Dusk in the Valley",
        "Loop of Mountains",
        "Wind and Corner",
        "Cozy Late Night",
        "Uplifting Wind",
        "Velvet Glow",
        "Dusk Lounge",
        "Room of Waves",
        "Afternoon Frames",
        "First Light in the Rain",
        "Sunrise Loop",
        "Branches and Harmony",
        "Sunny Sunrise",
        "Breezy Noon",
        "Cozy Steps",
        "Playful Breeze",
        "Hazy Starlight",
        "Flow of Starlight",
        "Whisper of Fields",
        "Uplifting Reflections",
        "Shore and Window",
        "Moments of Leaves",
        "Calm Cafe",
        "Frames of Garden",
        "Ocean and Whisper",
        "Sunset Reflections",
        "Twilight in the Forest",
        "Late Night Serenade",
        "Sunrise Steps",
        "Whisper of Meadow",
        "Morning Groove",
        "Breezy Late Night",
        "Noon Dream",
        "Hopeful Mountains",
        "Twilight Pages",
        "Mist and Chapters",
        "Reflections of Valley",
        "Soft Morning",
        "Easy Loop",
        "Late Night Stroll",
        "Morning Melody",
        "Groove of Wind",
        "Starlight and Stories",
        "Haze of Fields",
        "Wistful Stories",
        "Amber Chapters",
        "Late Night Frames",
        "Hopeful Morning",
        "Hazy Afternoon",
        "Peaceful Cafe",
        "Velvet Frames",
        "Mountains and Serenade",
        "Ivory Midnight",
        "Velvet Garden",
        "Luminous Corner",
        "Warm Branches",
        "Steps of Starlight",
        "Flow of Stream",
        "Golden Hour Room",
        "Midnight in the City",
        "Golden Clouds",
        "Ivory Afternoon",
        "Tranquil First Light",
        "Easy Morning",
        "Cheerful Starlight",
        "Branches and Lounge",
        "Golden Daybreak",
        "Shimmering Morning",
        "Uplifting Twilight",
        "Soft Flow",
        "Quiet Cafe",
        "Nightfall Harmony",
        "Cafe of Moonlight",
        "Cozy Sunrise",
        "Drift of River",
        "Moments of Petals",
        "Rhythm of Leaves",
        "River and Haze",
        "Whisper of Sunlight",
        "Stream and Light",
        "Breezy Letters",
        "Reflections of Wind",
        "Lazy Frames",
        "Sky and Chapters",
        "Quiet Waves",
        "Daybreak Lounge",
        "Wistful Ocean",
        "Peaceful First Light",
        "Mellow First Light",
        "Stories of Fog",
        "Sunrise in the Forest",
        "Dawn in the Cafe",
        "Sunny First Light",
        "Ocean and Reflections",
        "Pastel Sunrise",
        "Chill Sunrise",
        "Morning in the Valley",
        "Faint Lounge",
        "Tranquil Late Night",
        "Letters of Wind",
        "Frosted Nightfall",
        "Pastel Lounge",
        "Haze of Meadow",
        "Ocean and Loop",
        "Pastel Groove",
        "Shadows of Fog",
        "Daybreak Rhythm",
        "Uplifting Steps",
        "Twilight Room",
        "River and Letters",
        "Hopeful Stream",
        "Crimson Mountains",
        "Shore and Corner",
        "Late Night Harmony",
        "Playful Frames",
        "Sunrise Room",
        "Mountains and Cafe",
        "Midnight Whisper",
        "Dusk Stroll",
        "Petals and Dream",
        "Midnight in the Valley",
        "Soft Ocean",
        "Hopeful Evening",
        "Dusk Drift",
        "Faint Sunlight",
        "Letters of Forest",
        "Horizon and Rhythm",
        "Harmony of Clouds",
        "Branches and Chapters",
        "Amber Midnight",
        "Warm Nightfall",
        "Dusk in the Forest",
        "Petals and Frames",
        "Blissful Mountains",
        "Cheerful Stream",
        "Moonlight and Lounge",
        "Harmony of Sunlight",
        "Faint Branches",
        "Mist and Room",
        "Mist and Haze",
        "Reflections of Moonlight",
        "Pages of Branches",
        "Bright Cafe",
        "Mellow Leaves",
        "Meadow and Light",
        "Midnight Echo",
        "Hopeful Sunrise",
        "Bright Rain",
        "Sunset in the Rain",
        "Frames of Waves",
        "Cheerful Room",
        "Clouds and Loop",
        "Golden Morning",
        "Serene Leaves",
        "Faint Groove",
        "Petals and Reflections",
        "Fields and Haze",
        "Breezy Whisper",
        "Golden Evening",
        "Pages of Wind",
        "Faint Twilight",
        "Cozy Twilight",
        "Frosted Noon",
        "Breezy Stroll",
        "Chapters of Mist",
        "Daybreak Dream",
        "Frosted Daybreak",
        "Forest and Drift",
        "Bright Drift",
        "Evening Flow",
        "Dreamy Room",
        "Noon Cafe",
        "Shimmering Loop",
        "Sunlight and Stories",
        "Late Night Lounge",
        "Wistful Letters",
        "Cafe of Stream",
        "Afternoon in the City",
        "Nightfall Frames",
        "Serenade of Wind",
        "Warm Letters",
        "Dream of Garden",
        "Evening Drift",
        "Corner of Petals",
        "Sunlight and Serenade",
        "Hopeful Moments",
        "Quiet Chapters",
        "Peaceful Wind",
        "Noon in the Forest",
        "Sunlight and Drift",
        "Sky and Pages",
        "Uplifting River",
        "Steps of Sky",
        "Calm Wind",
        "Late Night Whisper",
        "Evening Corner",
        "Azure First Light",
        "Stream and Frames",
        "Nightfall in the City",
        "Frosted Corner",
        "Twilight Moments",
        "River and Dream",
        "Hazy Late Night",
        "Velvet Melody",
        "Fading Leaves",
        "Evening Sunlight",
        "Quiet Moments",
        "Frosted Loop",
        "Moments of Snow",
        "Sunset in the Garden",
        "First Light Melody",
        "Daybreak in the City",
        "Golden Hour Loop",
        "Chapters of Breeze",
        "Uplifting Dawn",
        "Golden Hour Moments",
        "Sunset Echo",
        "Frosted Cafe",
        "Echo of Breeze",
        "Soothing Frames",
        "Breeze and Stories",
        "Noon Chapters",
        "Amber Dawn",
        "Cheerful Wind",
        "Azure Sunrise",
        "Luminous Daybreak",
        "Afternoon Haze",
        "First Light Serenade",
        "Calm Dawn",
        "Noon Stroll",
        "Waves and Cafe",
        "Drowsy Haze",
        "Pastel Golden Hour",
        "Sunny Lounge",
        "Glow of Shore",
        "Lounge of Snow",
        "Pastel Afternoon",
        "Hopeful Dawn",
        "Soothing Drift",
        "Sunlight and Steps",
        "Bright Shore",
        "Uplifting Meadow",
        "Afternoon Groove",
        "Blissful Evening",
        "Azure Dream",
        "Meadow and Corner",
        "Sunset in the Forest",
        "Uplifting Chapters",
        "Twilight Echo",
        "Corner of Ocean",
        "Ivory Chapters",
        "Amber Petals",
        "Mountains and Letters",
        "Sunrise in the City",
        "Pages of Mountains",
        "Dawn Melody",
        "Golden Hour Echo",
        "Shimmering Stream",
        "Gentle Sky",
        "Serene Midnight",
        "Quiet Shadows",
        "Dusk Whisper",
        "Serene Ocean",
        "Mountains and Glow",
        "Chapters of Rain",
        "Sea and Flow",
        "Nightfall Chapters",
        "Nightfall Steps",
        "Amber Snow",
        "Moonlight and Harmony",
        "Lazy Late Night",
        "Fields and Melody",
        "Playful Mist",
        "Mountains and Stroll",
        "Drift of Starlight",
        "Midnight Groove",
        "Stories of Rain",
        "Dusk Frames",
        "Twilight Shadows",
        "Amber Light",
        "Lounge of Sky",
        "Evening Steps",
        "Garden and Flow",
        "Evening Dawn",
        "Warm Petals",
        "Gentle Ocean",
        "Shimmering Sky",
        "Drowsy Melody",
        "Golden Petals",
        "Pastel Moments",
        "Nightfall in the Cafe",
        "Pastel Breeze",
        "Dreamy Dawn",
        "Horizon and Stories",
        "Starlight and Groove",
        "Drowsy Nightfall",
        "Tranquil Sunlight",
        "Flow of Clouds",
        "Flow of Fog",
        "Dawn in the Forest",
        "Hopeful Light",
        "Light of Wind",
        "Dusk Dream",
        "Midnight in the Rain",
        "Chill Glow",
        "Soothing Shore",
        "Golden Hour in the Forest",
        "Morning in the Garden",
        "Sunset Lounge",
        "Breezy Branches",
        "Bright Pages",
        "Azure Snow",
        "Luminous Glow",
        "Velvet Morning",
        "Midnight River",
        "Gentle River",
        "Hopeful Fog",
        "Room of Horizon",
        "Chill Dawn",
        "Mist and Lounge",
        "Velvet Letters",
        "Blissful Stories",
        "Hopeful Corner",
        "Crimson Frames",
        "Serene Nightfall",
        "Rain and Haze",
        "Gentle Stream",
        "Noon Pages",
        "Meadow and Lounge",
        "Meadow and Reflections",
        "Nightfall Pages",
        "Chapters of Horizon",
        "Harmony of Fields",
        "Dusk Groove",
        "Dreamy Forest",
        "Blissful Starlight",
        "Shimmering Twilight",
        "Hazy Pages",
        "Corner of Shore",
        "Leaves and Whisper",
        "Dreamy Late Night",
        "Morning Snow",
        "Breeze and Window",
    ]
    
    print("🎵 Lofi Playlist Length Checker")
    print("🎯 Target: 30 songs per playlist")
    print("Choose an option:")
    print("1. Check only (no modifications)")
    print("2. Check and fix to exactly 30 songs (will modify the JSON file)")
    
    choice = input("\nEnter your choice (1 or 2): ").strip()
    
    if choice == "1":
        print("\n🔍 Running in CHECK-ONLY mode...")
        results = check_and_fix_playlist_lengths(json_file_path, backup_titles, fix_mode=False, target_length=30)
    elif choice == "2":
        if not backup_titles or len(backup_titles) == 0:
            print("\n❌ Error: No backup titles provided!")
            print("Please edit this script and add song titles to the 'backup_titles' list.")
            return
        
        print(f"\n📝 This will create a new JSON file with exactly 30 songs per playlist:")
        print("   - Playlists with < 30 songs: will add random titles from your backup list")
        print("   - Playlists with > 30 songs: will remove excess songs from the end")
        print("   - Original file will be preserved unchanged")
        print("   - Fixed data will be saved as: lofi_playlist_data_fixed.json")
        
        confirm = input("\nContinue? (y/N): ").strip().lower()
        if confirm != 'y':
            print("Operation cancelled.")
            return
            
        print("\n🔧 Running in FIX mode...")
        results = check_and_fix_playlist_lengths(json_file_path, backup_titles, fix_mode=True, target_length=30)
    else:
        print("Invalid choice. Exiting.")
        return
    
    print_report(results)
    
    if choice == "1" and results['incorrect_length_playlists']:
        print(f"\n💡 To fix these issues, run this script again and choose option 2.")
        print("   (Make sure to add your backup titles to the script first!)")

if __name__ == "__main__":
    main()